rule_files:
  - "metrics.yml"
scrape_configs:
- job_name: bookings
  scrape_interval: 10s
  metrics_path: '/bookings/metrics'
  static_configs:
  - targets:
    - booking_svc:8091
- job_name: hotels
  scrape_interval: 10s
  metrics_path: '/hotels/metrics'
  static_configs:
  - targets:
    - hotel_svc:8090