// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: hotel.proto

package protos

import (
	context "context"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HotelService_IsValidPersonID_FullMethodName    = "/hotel.HotelService/IsValidPersonID"
	HotelService_IsValidHotelID_FullMethodName     = "/hotel.HotelService/IsValidHotelID"
	HotelService_IsValidRoomID_FullMethodName      = "/hotel.HotelService/IsValidRoomID"
	HotelService_GetAllRoomsInHotel_FullMethodName = "/hotel.HotelService/GetAllRoomsInHotel"
	HotelService_GetRoomPrice_FullMethodName       = "/hotel.HotelService/GetRoomPrice"
)

// HotelServiceClient is the client API for HotelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HotelServiceClient interface {
	IsValidPersonID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	IsValidHotelID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	IsValidRoomID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	GetAllRoomsInHotel(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*Rooms, error)
	GetRoomPrice(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.FloatValue, error)
}

type hotelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHotelServiceClient(cc grpc.ClientConnInterface) HotelServiceClient {
	return &hotelServiceClient{cc}
}

func (c *hotelServiceClient) IsValidPersonID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, HotelService_IsValidPersonID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) IsValidHotelID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, HotelService_IsValidHotelID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) IsValidRoomID(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, HotelService_IsValidRoomID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) GetAllRoomsInHotel(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*Rooms, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rooms)
	err := c.cc.Invoke(ctx, HotelService_GetAllRoomsInHotel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hotelServiceClient) GetRoomPrice(ctx context.Context, in *wrappers.Int32Value, opts ...grpc.CallOption) (*wrappers.FloatValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrappers.FloatValue)
	err := c.cc.Invoke(ctx, HotelService_GetRoomPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HotelServiceServer is the server API for HotelService service.
// All implementations must embed UnimplementedHotelServiceServer
// for forward compatibility.
type HotelServiceServer interface {
	IsValidPersonID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error)
	IsValidHotelID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error)
	IsValidRoomID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error)
	GetAllRoomsInHotel(context.Context, *wrappers.Int32Value) (*Rooms, error)
	GetRoomPrice(context.Context, *wrappers.Int32Value) (*wrappers.FloatValue, error)
	mustEmbedUnimplementedHotelServiceServer()
}

// UnimplementedHotelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHotelServiceServer struct{}

func (UnimplementedHotelServiceServer) IsValidPersonID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValidPersonID not implemented")
}
func (UnimplementedHotelServiceServer) IsValidHotelID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValidHotelID not implemented")
}
func (UnimplementedHotelServiceServer) IsValidRoomID(context.Context, *wrappers.Int32Value) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsValidRoomID not implemented")
}
func (UnimplementedHotelServiceServer) GetAllRoomsInHotel(context.Context, *wrappers.Int32Value) (*Rooms, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRoomsInHotel not implemented")
}
func (UnimplementedHotelServiceServer) GetRoomPrice(context.Context, *wrappers.Int32Value) (*wrappers.FloatValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoomPrice not implemented")
}
func (UnimplementedHotelServiceServer) mustEmbedUnimplementedHotelServiceServer() {}
func (UnimplementedHotelServiceServer) testEmbeddedByValue()                      {}

// UnsafeHotelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HotelServiceServer will
// result in compilation errors.
type UnsafeHotelServiceServer interface {
	mustEmbedUnimplementedHotelServiceServer()
}

func RegisterHotelServiceServer(s grpc.ServiceRegistrar, srv HotelServiceServer) {
	// If the following call pancis, it indicates UnimplementedHotelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HotelService_ServiceDesc, srv)
}

func _HotelService_IsValidPersonID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).IsValidPersonID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelService_IsValidPersonID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).IsValidPersonID(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_IsValidHotelID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).IsValidHotelID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelService_IsValidHotelID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).IsValidHotelID(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_IsValidRoomID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).IsValidRoomID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelService_IsValidRoomID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).IsValidRoomID(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_GetAllRoomsInHotel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).GetAllRoomsInHotel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelService_GetAllRoomsInHotel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).GetAllRoomsInHotel(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

func _HotelService_GetRoomPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.Int32Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HotelServiceServer).GetRoomPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HotelService_GetRoomPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HotelServiceServer).GetRoomPrice(ctx, req.(*wrappers.Int32Value))
	}
	return interceptor(ctx, in, info, handler)
}

// HotelService_ServiceDesc is the grpc.ServiceDesc for HotelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HotelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hotel.HotelService",
	HandlerType: (*HotelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsValidPersonID",
			Handler:    _HotelService_IsValidPersonID_Handler,
		},
		{
			MethodName: "IsValidHotelID",
			Handler:    _HotelService_IsValidHotelID_Handler,
		},
		{
			MethodName: "IsValidRoomID",
			Handler:    _HotelService_IsValidRoomID_Handler,
		},
		{
			MethodName: "GetAllRoomsInHotel",
			Handler:    _HotelService_GetAllRoomsInHotel_Handler,
		},
		{
			MethodName: "GetRoomPrice",
			Handler:    _HotelService_GetRoomPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hotel.proto",
}
