openapi: 3.0.0
info:
  title: Hotel Booking System API
  description: API для системы бронирования отелей, включающая сервисы бронирования, отелей, уведомлений и оплаты.
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /bookings:
    post:
      summary: Создание нового бронирования
      description: Этот эндпоинт используется для создания нового бронирования отеля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client_id:
                  type: integer
                  description: Идентификатор клиента, который делает бронирование.
                hotel_id:
                  type: integer
                  description: Идентификатор отеля, в котором будет сделано бронирование.
                room_id:
                  type: integer
                  description: Идентификатор комнаты, в которой будет сделано бронирование.
                check_in_date:
                  type: string
                  format: date
                  description: Дата заезда.
                check_out_date:
                  type: string
                  format: date
                  description: Дата выезда.
                payment_method:
                  type: string
                  description: Способ оплаты.
              required:
                - client_id
                - hotel_id
                - room_id
                - check_in_date
                - check_out_date
      responses:
        '201':
          description: Бронирование успешно создано.
          content:
            application/json:
              schema:
                type: object
                properties:
                  booking_id:
                    type: string
                    description: Идентификатор созданного бронирования.
        '400':
          description: Неверные данные для бронирования.
        '403':
          description: Бронирование недосутпно.
        '500':
          description: Внутренняя ошибка сервера.
  
  /bookings/get?id={booking_id}:
    get:
      summary: Получить информацию о брони по booking_id
      responses:
        '200':
          description: Информация о броне успешна получена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking" 
        '400':
          description: Неверный booking_id
        '500':
          description: Внутренняя ошибка сервера.
  
  /bookings/hotel/get?id={hotel_id}:
    get:
      summary: Получить информацию о всех бронях в отеле
      responses:
        '200':
          description: Информация о бронях успешна получена.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"
        '400':
          description: Неверный hotel_id
        '500':
          description: Внутренняя ошибка сервера.

  /bookings/client/get?id={client_id}:
    get:
      summary: Получить информацию о всех бронях клиента
      responses:
        '200':
          description: Информация о бронях успешна получена.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"
        '400':
          description: Неверный client_id
        '500':
          description: Внутренняя ошибка сервера.
  
  /bookings/hotel/available?id={hotel_id}:
    get:
      summary: Get all available bookings in the hotel
      responses:
        '200':
          description: List of available bookings in the hotel
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"
        '400':
          description: Неверный hotel_id
        '500':
          description: Внутренняя ошибка сервера.
              

  /hotels:
    get:
      summary: Получение информации о всех отелях
      description: Этот эндпоинт позволяет получить список всех отелей с их данными (например, номера, цены).
      responses:
        '200':
          description: Список отелей успешно получен.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hotel"
        '500':
          description: Внутренняя ошибка сервера.
    post:
      summary: Создание нового отеля
      description: Этот эндпоинт используется для создания нового отеля в системе.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner_id:
                  type: integer
                  description: Идентификатор владельца, который оформляет отель.
                name:
                  type: string
                  description: Имя отеля.
                location:
                  type: string
                  description: Локация отеля.
                rooms:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      price:
                        type: number
                        format: float
              required:
                - owner_id
                - name
                - location
                - rooms
      responses:
        '201':
          description: Отель успешно создан.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hotel_id:
                    type: string
                    description: Идентификатор созданного отеля.
        '400':
          description: Неверные данные.
        '500':
          description: Внутренняя ошибка сервера.

  /hotels/get?id={hotel_id}:
    get:
      summary: "Получить информацию об отеле по hotel_id"
      responses:
        '200':
          description: Информация об отеле успешна получена.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hotel" 
        '400':
          description: Неверный hotel_id
        '500':
          description: Внутренняя ошибка сервера.
  
  /hotels/owner/get?id={owner_id}:
    get:
      summary: "Получить информацию о всех отелях у владельца по owner_id"
      responses:
        '200':
          description: Информация об отелях успешна получена.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hotel" 
        '400':
          description: Неверный owner_id
        '500':
          description: Внутренняя ошибка сервера.
    
  /hotel/room:
    delete:
      summary: Удалить комнату из отеля
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hotel_id:
                  type: integer
                room_id:
                  type: integer
              required:
                - hotel_id
                - room_id
      responses:
        '201':
          description: Комната успешно удалена
        '400':
          description: Неверные данные.
        '403':
          description: Удаление невозможно.
        '500':
          description: Внутренняя ошибка сервера.
    put:
      summary: Обновить информацию об комнате
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: integer
                hotel_id:
                  type: integer
                type:
                  type: string
                price:
                  type: number
                  format: float
              required:
                - hotel_id
                - room_id
                - type
                - price
      responses:
        '200':
          description: Комната успешно обновлена
        '400':
          description: Неверные данные.
        '403':
          description: Обновление невозможно.
        '500':
          description: Внутренняя ошибка сервера.
    post:
      summary: Создать новую комнату
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hotel_id:
                  type: integer
                type:
                  type: string
                price:
                  type: number
                  format: float
              required:
                - hotel_id
                - type
                - price
      responses:
        '201':
          description: Комната успешно создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  room_id:
                    type: string
                    description: Идентификатор.
        '400':
          description: Неверные данные.
        '500':
          description: Внутренняя ошибка сервера.

  /notifications:
    post:
      summary: Отправка уведомлений
      description: Этот эндпоинт используется для отправки уведомлений клиентам и отельерам о статусе бронирования.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient_id:
                  type: string
                  description: Идентификатор получателя уведомления.
                message:
                  type: string
                  description: Текст уведомления.
              required:
                - recipient_id
                - message
                - type
      responses:
        '200':
          description: Уведомление успешно отправлено.
        '400':
          description: Ошибка в данных уведомления.
        '500':
          description: Внутренняя ошибка сервера.

  /payment:
    post:
      summary: Создание заявки на оплату
      description: Этот эндпоинт используется для создания заявки на оплату бронирования отеля.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  description: Идентификатор бронирования, для которого требуется оплата.
                amount:
                  type: number
                  format: float
                  description: Сумма оплаты.
                payment_method:
                  type: string
                  description: Способ оплаты.
              required:
                - booking_id
                - amount
                - payment_method
      responses:
        '200':
          description: Заявка на оплату успешно создана.
        '400':
          description: Ошибка в данных оплаты.
        '500':
          description: Внутренняя ошибка сервера.

  /webhooks/payment:
    post:
      summary: Вебхук для уведомления о статусе оплаты
      description: Этот эндпоинт используется для получения уведомлений о статусе оплаты бронирования.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  description: Идентификатор бронирования, оплата которого была проведена.
                status:
                  type: string
                  enum: [success, failure]
                  description: Статус оплаты (успех или неудача).
                transaction_id:
                  type: string
                  description: Идентификатор транзакции.
              required:
                - booking_id
                - status
      responses:
        '200':
          description: Статус оплаты успешно обновлен.
        '400':
          description: Ошибка в данных статуса оплаты.
        '500':
          description: Внутренняя ошибка сервера.

components:
  schemas:
    Booking:
      type: object
      properties:
        booking_id:
          type: integer
        client_id:
          type: integer
        hotel_id:
          type: integer
        room_id:
          type: integer
        check_in_date:
          type: string
          format: date
        check_out_date:
          type: string
          format: date
        status:
          type: string
          enum: [pending, confirmed, cancelled]
    Hotel:
      type: object
      properties:
        owner_id:
          type: integer
        hotel_id:
          type: integer
        name:
          type: string
        location:
          type: string
        rooms:
          type: array
          items:
            type: object
            properties:
              room_id:
                type: string
              type:
                type: string
              price:
                type: number
                format: float
    Notification:
      type: object
      properties:
        recipient_id:
          type: integer
        message:
          type: string
    Payment:
      type: object
      properties:
        booking_id:
          type: integer
        amount:
          type: number
          format: float
        payment_method:
          type: string
